HMS.UI/Controllers/DoctorController.cs
using HMS.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace HMS.UI.Controllers
{
    public class DoctorController : Controller
    {
        
        private IConfiguration _configuration;
        public DoctorController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> DoctorIndex()
        {
            IEnumerable<Doctor> doctorresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Doctor/GetDoctors";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        doctorresult = JsonConvert.DeserializeObject<IEnumerable<Doctor>>(result);
                    }
                }
            }
            return View(doctorresult);
        }
        public IActionResult AddDoctor()
        {
            return View();
        }
        [HttpPost("AddDoctor")]
        public async Task<IActionResult> AddDoctor(Doctor doctor)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(doctor), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Doctor/AddDoctor";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "  Doctor details saved successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
        [HttpPut("UpdateDoctor")]
        public async Task<IActionResult> UpdateDoctor(Doctor doctor)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(doctor), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Doctor/UpdateDoctor";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "  Doctor details edited successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
    }
}

HMS.UI/Views/Doctor/AddDoctor.cshtml
@model HMS.Entity.Models.Doctor

@{
    ViewData["Title"] = "AddDoctor";
}
<form method="post" enctype="multipart/form-data">
    <h1>Doctor Registration</h1>
</form>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddDoctor">
            <div class="form-group">
                <label asp-for="DoctorName" class="control-label"></label>
                <input asp-for="DoctorName" class="form-control" id="validationTooltip01" value="" required />
                <div class="valid-tooltip">
                    Looks good!
                </div>
            </div>
            <div class="form-group">
                <label asp-for="DoctorQualification" class="control-label"></label>
                <input asp-for="DoctorQualification" class="form-control" id="validationTooltip01" value="" required />
                <div class="valid-tooltip">
                    Looks good!
                </div>
            </div>
                <div class="form-group">
                    <label asp-for="DoctorSpecialization" class="control-label"></label>
                    <input asp-for="DoctorSpecialization" class="form-control" id="validationTooltip01" value="" required />
                    <span asp-validation-for="DoctorSpecialization" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ConsultFee" class="control-label"></label>
                    <input asp-for="ConsultFee" class="form-control" id="validationTooltip01" value="" required />
                    <span asp-validation-for="ConsultFee" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" placeholder="name@example.com" id="validationTooltip01" value="" required>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" id="validationTooltip01" value="" required />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" id="validationTooltipPassword" aria-describedby="validationTooltipPassword" required />
                    <span asp-validation-for="Password" class="text-danger"></span>
                    <div class="invalid-tooltip">
                        Please choose a unique and valid Password.
                    </div>
                </div>
                <div class="form-group">
                    <label for="validationTooltip04"
                           asp-for="ReEnterPassword"class="control-label"></label>
                    <input asp-for="ReEnterPassword" class="form-control"  id="validationTooltip01" value="" required/>
                    <span asp-validation-for="ReEnterPassword" class="text-danger"></span>
                    <div class="invalid-tooltip">
                        Password is not matching.
                    </div>
                </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                    @if (ViewBag.status == "Ok")
                    {
                        <div class="alert alert-success">
                            @ViewBag.message
                        </div>
                    }
                    else if (ViewBag.status == "Error")
                    {
                        <div class="alert alert-danger">
                            @ViewBag.message
                        </div>
                    }
</form>
    </div>
</div>

HMS.UI/Views/Doctor/DoctorIndex.cshtml
@model IEnumerable<HMS.Entity.Models.Doctor>
@{ 
    Layout = "~/shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <h3>Doctor Registration History</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Doctor Id</th>
                    <th>Doctor Name</th>
                    <th> Doctor Qualification</th>
                    <th> Doctor Specilization</th>
                    <th>Consult Fee </th>
                    <th> Email</th>
                    <th> Phone Number</th>
                    <th>Password </th>
                    <th> ReEnter Password</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>


                @foreach (var doctor in Model)
                {

                    <tr>
                        <td>@doctor.DoctorId</td>
                        <td>@doctor.DoctorName</td>
                        <td>@doctor.DoctorQualification</td>
                        <td>@doctor.DoctorSpecialization</td>
                        <td>@doctor.ConsultFee</td>
                        <td>@doctor.Email</td>
                        <td>@doctor.PhoneNumber</td>
                        <td>@doctor.Password</td>
                        <td>@doctor.ReEnterPassword</td>



                        <td><a asp-controller="Doctor" asp-action="UpdateDoctor" asp-route-MovieId="@doctor.DoctorId">Update</a></td>
                        <td><a asp-controller="Doctor" asp-action="DeleteDoctor" asp-route-MovieId="@doctor.DoctorId">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>