HMS.UI/Controllers/EmployeeController.cs
using HMS.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace HMS.UI.Controllers
{
    public class EmployeeController : Controller
    {
        private IConfiguration _configuration;
        public EmployeeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> EmployeeIndex()
        {
            IEnumerable<Employee> employeeresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Employee/GetEmployees";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        employeeresult = JsonConvert.DeserializeObject<IEnumerable<Employee>>(result);
                    }
                }
            }
            return View(employeeresult);
        }
        public IActionResult AddEmployee()
        {
            return View();
        }
        [HttpPost("AddEmployee")]
        public async Task<IActionResult> AddEmployee(Employee employee)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employee), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Employee/AddEmployee";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "  Employee details saved successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
        [HttpPut("UpdateEmployee")]
        public async Task<IActionResult> UpdateEmployee(Employee employee)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employee), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Doctor/UpdateEmployee";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "  Doctor details edited successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
    }
}

HMS.UI/Views/Employee/AddEmployee.cshtml
@model HMS.Entity.Models.Employee

@{
    ViewData["Title"] = "AddEmployee";
}
<form method="post" enctype="multipart/form-data">
    <h1>Employee Registration</h1>
</form>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddEmployee">
            <div class="form-group">
                <label asp-for="EmployeeName" class="control-label"></label>
                <input asp-for="EmployeeName" class="form-control" id="validationTooltip01" value="" required/>
                <span asp-validation-for="EmployeeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeRole" class="control-label"></label>
                <input asp-for="EmployeeRole" class="form-control" id="validationTooltip01" value="" required />
                <span asp-validation-for="EmployeeRole" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" id="validationTooltip01" value="" required/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" id="validationTooltip01" value="" required/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" id="validationTooltip01" value="" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReEnterPassword" class="control-label"></label>
                <input asp-for="ReEnterPassword" class="form-control" id="validationTooltip01" value="" required/>
                <span asp-validation-for="ReEnterPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
            @if (ViewBag.status == "Ok")
            {
                <div class="alert alert-success">
                    @ViewBag.message
                </div>
            }
            else if (ViewBag.status == "Error")
            {
                <div class="alert alert-danger">
                    @ViewBag.message
                </div>
            }
        </form>
    </div>
</div>

HMS.UI/Views/Employee/EmployeeIndex.cshtml
@model IEnumerable<HMS.Entity.Models.Employee>

<div class="row">
    <div class="col-12">
        <h3>Employee Registration History</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Employee ID</th>
                    <th>Employee Name</th>
                    <th> Employee Role</th>
                    <th> Email</th>
                    <th> Phone Number</th>
                    <th>Password </th>
                    <th> ReEnter Password</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>


                @foreach (var employee in Model)
                {

                    <tr>
                        <td>@employee.EmployeeId</td>
                        <td>@employee.EmployeeName</td>
                        <td>@employee.EmployeeRole</td>
                        <td>@employee.Email</td>
                        <td>@employee.PhoneNumber</td>
                        <td>@employee.Password</td>
                        <td>@employee.ReEnterPassword</td>



                        <td><a asp-controller="Employee" asp-action="UpdateEmployee" asp-route-MovieId="@employee.EmployeeId">Update</a></td>
                        <td><a asp-controller="Employee" asp-action="DeleteEmployee" asp-route-MovieId="@employee.EmployeeId">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>